version: '3.8'

services:
  ai-deepface:
    build: ./model-deepFace
    container_name: model-deepface
    environment:
      - VIDEO_URL=http://host.docker.internal:8080/video_feed
      - DATA_ENDPOINT=http://data-collector:5000/data
    ports:
      - "8090:8090"
    depends_on:
      - data-collector
    networks:
      - ai-network
    restart: always

  data-collector:
    build: ./data_collector
    container_name: data-collector
    ports:
      - "5000:5000"
    networks:
      - ai-network
    restart: always

networks:
  ai-network:
    driver: bridge